ERROR = {
    "status": False,
    "message": "Ocurrio un error en sunat"
}

LABELS = {
    "Numero Ruc": "ruc",
    "NumeroRuc": "ruc",
    "Nombre / Razón Social": "razon_social",
    "Nombre ó RazonSocial": "razon_social",
    "Tipo de Contribuyente": "tipo_contribuyente",
    "Profesión u Oficio": "oficio",
    "Profesion u Oficio": "oficio",
    "Nombre Comercial": "nombre_comercial",
    "Condición del Contribuyente": "condicion_contribuyente",
    "Condicion del Contribuyente": "condicion_contribuyente",
    "Estado Contribuyente": "estado_contribuyente",
    "Estado del Contribuyente": "estado_contribuyente",
    "Fecha de Inscripción": "fecha_inscripcion",
    "Fecha de Inscripcion": "fecha_inscripcion",
    "Fecha de Inicio de Actividades": "fecha_inicio",
    "Departamento": "departamento",
    "Provincia": "provincia",
    "Distrito": "distrito",
    "Dirección": "direccion",
    "Direccion": "direccion",
    "Telefono (s)": "telefono",
    "Telefono": "telefono",
    "Fax": "fax",
    "Actividad de Comercio Exterior": "actividad_exterior",
    "Actividad de Comercio Exterior": "actividad_exterior_2",
    "Principal- CIIU": "principal_ciiu",
    "Secundario 1- CIIU": "secundario_ciiu_1",
    "Secundario 2- CIIU": "secundario_ciiu_2",
    "Nuevo RUS": "nuevo_rus",
    "Afecto Nuevo RUS": "nuevo_rus",
    "Buen Contribuyente": "buen_contribuyente",
    "Agentes de Retención del IGV": "retencion_igv",
    "Agente de Retencion": "retencion_igv",
    "Agentes de Percepción IGV-Venta Interna": "percepcion_igv_venta_interna",
    "Agente de Percepcion VtaInt": "percepcion_igv_venta_interna",
    "Agentes de Percepción IGV-Combustible Líquido": "percepcion_igv_combustible_liquido",
    "Agente de Percepcion ComLiq": "percepcion_igv_combustible_liquido",
    "\n": "developer"
}
